### ISSUE TITLE
Positions API expiry Date Inconsistent

### ISSUE THREAD

**Issue by chandra-mrinal** [IIFLSecurities/IIFL-Markets-Open-API-Postman-Collection-Official-#33]
in the response of /positions API below, we are getting formattedInstrumentName as "NIFTY 23 Apr 2025" . we assumed this to be the expiry date.
But the expected expiry date should be 24 Apr 2025.

`Current positions: {
  "status": "Ok",
  "message": "Success",
  "result": [
    {
      "instrumentId": "79203",
      "tradingSymbol": "NIFTY25APR20450PE",
      "formattedInstrumentName": "NIFTY 23 Apr 2025",
      "exchange": "NSEFO",
      "product": "NORMAL",
      "realizedPnl": 0.0,
      "netQuantity": -75,
      "netAveragePrice": 1.05,
      "overnightQuantity": 0,
      "overnightPrice": 0.0,
      "buyQuantity": 0,
      "buyPrice": 0.0,
      "sellQuantity": 75,
      "sellPrice": 1.05,
      "dayBuyQuantity": 0,
      "dayBuyPrice": 0.0,
      "dayBuyValue": 0.0,
      "daySellQuantity": 75,
      "daySellPrice": 1.05,
      "daySellValue": 78.75,
      "multiplier": 1,
      "lotsize": 75,
      "ticksize": 0.05,
      "previousDayClose": 1.1
    },
    {
      "instrumentId": "79201",
      "tradingSymbol": "NIFTY25APR20400PE",
      "formattedInstrumentName": "NIFTY 23 Apr 2025",
      "exchange": "NSEFO",
      "product": "NORMAL",
      "realizedPnl": 0.0,
      "netQuantity": 75,
      "netAveragePrice": 1.2,
      "overnightQuantity": 0,
      "overnightPrice": 0.0,
      "buyQuantity": 75,
      "buyPrice": 1.2,
      "sellQuantity": 0,
      "sellPrice": 0.0,
      "dayBuyQuantity": 75,
      "dayBuyPrice": 1.2,
      "dayBuyValue": 90.0,
      "daySellQuantity": 0,
      "daySellPrice": 0.0,
      "daySellValue": 0.0,
      "multiplier": 1,
      "lotsize": 75,
      "ticksize": 0.05,
      "previousDayClose": 1.15
    }
  ]
}`

**Comment by openapisupport** [comment]
Hi Minal,

This seems to be a bug , we've informed the team and will update you soon.

Regards,
IIFL App Support.

**Comment by adityasoni-marketfeed** [comment]
Hi @openapisupport, can you please share an update on the above issue

**Comment by KumarVishalGuptaIIFL** [comment]
The issue has been resolved now. If you still observe this, please highlight it.

**Comment by chandra-mrinal** [comment]
this is still happening !
request URL: "positions"
request method: "GET"
request params: null
request payload: null
```
Current positions: {
  "status": "Ok",
  "message": "Success",
  "result": [
    {
      "instrumentId": "79207",
      "tradingSymbol": "NIFTY25APR20500PE",
      "formattedInstrumentName": "NIFTY 23 Apr 2025",
      "exchange": "NSEFO",
      "product": "NORMAL",
      "realizedPnl": -3.75,
      "netQuantity": 0,
      "netAveragePrice": 0.0,
      "overnightQuantity": 0,
      "overnightPrice": 0.0,
      "buyQuantity": 75,
      "buyPrice": 0.15,
      "sellQuantity": 75,
      "sellPrice": 0.1,
      "dayBuyQuantity": 75,
      "dayBuyPrice": 0.15,
      "dayBuyValue": 11.25,
      "daySellQuantity": 75,
      "daySellPrice": 0.1,
      "daySellValue": 7.5,
      "multiplier": 1,
      "lotsize": 75,
      "ticksize": 0.05,
      "previousDayClose": 1.0
    }
  ]
}
```

**Comment by KumarVishalGuptaIIFL** [comment]
Let us check and come back.

**Comment by openapisupport** [comment]
Hi Mrinal,

The issue has been resolved.

Regards,
IIFL App Support
